//================ export actiontype
//[PRODUCT REQ
export const PRODUCT_REQ = "PRODUCT_REQ";
export const PRODUCT_REQ_SUCCESS = "PRODUCT_REQ_SUCCESS";
export const PRODUCT_REQ_FAILD = "PRODUCT_REQ_FAILD";
//BRAND REQ
export const BRAND_REQ = "BRAND_REQ";
export const BRAND_REQ_SUCCESS = "BRAND_REQ_SUCCESS";
export const BRAND_REQ_FAILD = "BRAND_REQ_FAILD";
//BRAND CREATE
export const BRAND_REQ_CREATE = "BRAND_REQ_CREATE";
export const BRAND_REQ_CREATE_SUCCESS = "BRAND_REQ_CREATE_SUCCESS";
export const BRAND_REQ_CREATE_FAILD = "BRAND_REQ_CREATE_FAILD";
//BRAND DELETE
export const BRAND_REQ_DELETE = "BRAND_REQ_DELETE";
export const BRAND_REQ_DELETE_SUCCESS = "BRAND_REQ_DELETE_SUCCESS";
export const BRAND_REQ_DELETE_FAILD = "BRAND_REQ_DELETE_FAILD";
//BRAND UPDATE
export const BRAND_REQ_UPDATE = "BRAND_REQ_UPDATE";
export const BRAND_REQ_UPDATE_SUCCESS = "BRAND_REQ_UPDATE_SUCCESS";
export const BRAND_REQ_UPDATE_FAILD = "BRAND_REQ_UPDATE_FAILD";
//BRAND STATUS UPDATE
export const BRAND_REQ_STATUS = "BRAND_REQ_STATUS";
export const BRAND_REQ_STATUS_SUCCESS = "BRAND_REQ_STATUS_SUCCESS";
export const BRAND_REQ_STATUS_FAILD = "BRAND_REQ_STATUS_FAILD";

//CATAGORY REQ
export const CATAGORY_REQ = "CATAGORY_REQ";
export const CATAGORY_REQ_SUCCESS = "CATAGORY_REQ_SUCCESS";
export const CATAGORY_REQ_FAILD = "CATAGORY_REQ_FAILD";
//CATAGORY CREATE
export const CATAGORY_REQ_CREATE = "CATAGORY_REQ_CREATE";
export const CATAGORY_REQ_CREATE_SUCCESS = "CATAGORY_REQ_CREATE_SUCCESS";
export const CATAGORY_REQ_CREATE_FAILD = "CATAGORY_REQ_CREATE_FAILD";
//CATAGORY DELETE
export const CATAGORY_REQ_DELETE = "CATAGORY_REQ_DELETE";
export const CATAGORY_REQ_DELETE_SUCCESS = "CATAGORY_REQ_DELETE_SUCCESS";
export const CATAGORY_REQ_DELETE_FAILD = "CATAGORY_REQ_DELETE_FAILD";
//CATAGORY UPDATE
export const CATAGORY_REQ_UPDATE = "CATAGORY_REQ_UPDATE";
export const CATAGORY_REQ_UPDATE_SUCCESS = "CATAGORY_REQ_UPDATE_SUCCESS";
export const CATAGORY_REQ_UPDATE_FAILD = "CATAGORY_REQ_UPDATE_FAILD";
//CATAGORY STATUS UPDATE
export const CATAGORY_REQ_STATUS = "CATAGORY_REQ_STATUS";
export const CATAGORY_REQ_STATUS_SUCCESS = "CATAGORY_REQ_STATUS_SUCCESS";
export const CATAGORY_REQ_STATUS_FAILD = "CATAGORY_REQ_STATUS_FAILD";

//TAG REQ
export const TAG_REQ = "TAG_REQ";
export const TAG_REQ_SUCCESS = "TAG_REQ_SUCCESS";
export const TAG_REQ_FAILD = "TAG_REQ_FAILD";
//TAG CREATE
export const TAG_REQ_CREATE = "TAG_REQ_CREATE";
export const TAG_REQ_CREATE_SUCCESS = "TAG_REQ_CREATE_SUCCESS";
export const TAG_REQ_CREATE_FAILD = "TAG_REQ_CREATE_FAILD";
//TAG DELETE
export const TAG_REQ_DELETE = "TAG_REQ_DELETE";
export const TAG_REQ_DELETE_SUCCESS = "TAG_REQ_DELETE_SUCCESS";
export const TAG_REQ_DELETE_FAILD = "TAG_REQ_DELETE_FAILD";
//TAG UPDATE
export const TAG_REQ_UPDATE = "TAG_REQ_UPDATE";
export const TAG_REQ_UPDATE_SUCCESS = "TAG_REQ_UPDATE_SUCCESS";
export const TAG_REQ_UPDATE_FAILD = "TAG_REQ_UPDATE_FAILD";
//TAG STATUS UPDATE
export const TAG_REQ_STATUS = "TAG_REQ_STATUS";
export const TAG_REQ_STATUS_SUCCESS = "TAG_REQ_STATUS_SUCCESS";
export const TAG_REQ_STATUS_FAILD = "TAG_REQ_STATUS_FAILD";
